# Generated by Django 4.0.5 on 2022-06-27 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=255)),
                ('telefono_alumno', models.IntegerField()),
                ('email_alumno', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lecciones', models.CharField(max_length=255)),
                ('horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesor', models.CharField(max_length=255)),
                ('email_profesor', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_profesor', models.IntegerField()),
                ('lecciones', models.ManyToManyField(to='webapp.lecciones')),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.alumnos')),
                ('nombre_lecciones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.lecciones')),
            ],
        ),
    ]
