# Generated by Django 4.0.5 on 2022-06-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_profesor_lecciones_profesor_lecciones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calificaciones',
        ),
    ]
