# Generated by Django 4.0.5 on 2022-06-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_delete_calificaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='email_alumno',
            new_name='email_alumnos',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='nombre_alumno',
            new_name='nombre_alumnos',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='telefono_alumno',
            new_name='telefono_alumnos',
        ),
    ]
