# Generated by Django 4.0.5 on 2022-06-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_email_alumno_alumnos_email_alumnos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='lecciones',
        ),
        migrations.AddField(
            model_name='profesor',
            name='lecciones',
            field=models.ManyToManyField(to='webapp.lecciones'),
        ),
    ]
