# Generated by Django 4.0.5 on 2022-06-27 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_profesor_lecciones_profesor_lecciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='telefono_alumnos',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='telefono_profesor',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_curso', models.CharField(max_length=7)),
                ('lecciones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.lecciones')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.profesor')),
            ],
        ),
    ]
