# Generated by Django 4.0.5 on 2022-06-28 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_alumnos_telefono_alumnos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecciones',
            name='temario',
            field=models.FileField(null=True, upload_to='static/'),
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='lecciones',
        ),
        migrations.AddField(
            model_name='profesor',
            name='lecciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.lecciones'),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
