# Generated by Django 4.0.5 on 2022-06-28 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_lecciones_temario_remove_profesor_lecciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('alumnos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.alumnos')),
                ('lecciones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.lecciones')),
            ],
        ),
    ]
