# Generated by Django 4.0.5 on 2022-07-05 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_lecciones_temario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='lecciones',
        ),
        migrations.AddField(
            model_name='lecciones',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.profesor'),
        ),
    ]
