# Generated by Django 4.0.5 on 2022-07-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_profesor_lecciones_lecciones_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='email_profesor',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='telefono_profesor',
        ),
    ]
