# Generated by Django 4.0.5 on 2022-07-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_alumnos_telefono_alumnos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='lecciones',
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='alumnos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.alumnos'),
        ),
    ]
