# Generated by Django 4.0.5 on 2022-07-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_remove_calificaciones_lecciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='alumnos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.alumnos'),
        ),
    ]
