# Generated by Django 4.0.5 on 2022-07-06 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_calificaciones_alumnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='lecciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.lecciones'),
        ),
    ]
