# Generated by Django 4.0.5 on 2022-07-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_calificaciones_lecciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='lecciones',
        ),
    ]
